version: "3"

services:
  backend:
    image: sample-app:backend
    build:
      context: .
      # dockerfile: Dockerfile.multistage
    ports:
      - 8080:8080
    environment:
      GREET_NAME: CWiCS BOOST attendees

