version: "3"

services:
  backend:
    image: sample-app:backend
    build:
      context: .
      # dockerfile: Dockerfile.multistage
    ports:
      - 8080:8080
    networks:
      - default
      - backend
    environment:
      GREET_NAME: CWiCS BOOST attendees
    expose:
      - 8080

  simplenginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ui:/usr/share/nginx/html/ui/
    ports:
      - 8081:8080

  fancynginx:
    image: sample-app:frontend
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8082:8080
    networks:
      - backend

  blockednginx:
    image: sample-app:frontend
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8083:8080
    networks:
      - sample

networks:
  backend:
  sample:
